### ISSUE TITLE
Melhorias na Documentação do Repositório

### ISSUE THREAD

**Issue by stephan-lopes** [slackjeff/journalNet#1]
## Descrição

Melhorar a documentação (README.md) do repositório, deixando ele mais detalhado quanto ao projeto, e para qual finalidade ele serve. Além disso, demonstrar como as pessoas podem contribuir com suas ideias.

Adicionar algum campo de Tarefas (ou então abrir issues com melhorias pendentes), pode ser útil para receber mais contribuições.

## Motivação

Gostei do projeto, e gostaria que o mesmo evolua (mesmo que seja algo para uso pessoal ou que evolua para algo em C, como comentado no [video](https://youtu.be/A1C2UqBsqmw)). 

## Tarefas

Seguindo o que foi informado na descrição, a minha sugestão de melhoria seria a seguinte:

- [x] Resumo do Projeto no README.md
- [x] Adicionar ao README.md, informações de como contribuir com o projeto
- [ ] Criação de Issues/To Do para novas features planejadas

## Critério de Aceite
- Ter o Resumo do Projeto dentro do README.md, e informações de como contribuir
- Local contendo informações das novas features a serem desenvolvidas (e que necessitam de apoio)

## Outras Informações 

O link para o Vídeo, contendo as informações de novas features e sobre o projeto, podem ser encontradas neste link: [https://youtu.be/A1C2UqBsqmw](https://youtu.be/A1C2UqBsqmw)

**Comment by Demogorgoff** [comment]
Olá Stephan!

Você poderia enviar um feedback sobre como ficou o novo README e a nova Documentação?
Você tem alguma sugestão e código de novas funções para serem implementadas?

Atenciosamente,
Demogorgoff.

**Comment by stephan-lopes** [comment]
> Olá Stephan!
> 
> 
> 
> Você poderia enviar um feedback sobre como ficou o novo README e a nova Documentação?
> 
> Você tem alguma sugestão e código de novas funções para serem implementadas?
> 
> 
> 
> Atenciosamente,
> 
> Demogorgoff.

Opa, ficou bem legal 😁!
